### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by MSandro** [batmanatorul/minesettlements-issues#5]
- [ ] I am using the latest version of the mod
- [ ] I checked if this bug report it's not a duplicate

**Information**
 - Mod Version 0.7
 - Minecraft Version 1.18.2

**Describe the bug**
once I have placed the lumber jack the world was stuck.

**To Reproduce**
place a town hall
place the lumber jack
click on build
world is now stuck

**Expected behavior**

**Log**
```
[12:30:01] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2846@5e4eed42, suppressing error
java.lang.NullPointerException: Cannot invoke "com.batmanatorul.minesettlements.managers.Settlement.unClaimChunks()" because "settlement" is null
	at com.batmanatorul.minesettlements.buildings.blocks.TownHallBlock.method_9536(TownHallBlock.java:75) ~[Minesettlements-0.7.jar:?]
	at net.minecraft.class_4970$class_4971.method_26197(class_4970.java:915) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818.method_12010(class_2818.java:250) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_30092(class_1937.java:211) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8652(class_1937.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_8650(class_1937.java:271) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14266(class_3225.java:258) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_21717(class_3225.java:230) ~[client-intermediary.jar:?]
	at net.minecraft.class_3225.method_14263(class_3225.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12066(class_3244.java:1030) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_12361(class_2846.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_2846.method_11054(class_2846.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by batmanatorul** [comment]
The error will be fixed in the next version, but idk how the world can be stuck, as i see from the log you broke a town hall block and it gave this error.. nothing to do with lumberjack
