### ISSUE TITLE
mod conflicts?

### ISSUE THREAD

**Issue by Omegarte** [batmanatorul/minesettlements-issues#6]
Minesettlements and possibly dimensional doors and/or pehkui mods conflict with each other?  When I disable minesettlements, the client loads fine.  When enabled, client crashes on startup. 
---------------------- 

Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'dimdoors'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.minecraft.class_4668.<clinit>(class_4668.java:125)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.putCutout(DimensionalDoorBlockRegistrar.java:73)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.register(DimensionalDoorBlockRegistrar.java:68)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.handleEntry(DimensionalDoorBlockRegistrar.java:53)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.lambda$init$0(DimensionalDoorBlockRegistrar.java:47)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.init(DimensionalDoorBlockRegistrar.java:47)
	at org.dimdev.dimdoors.block.door.DimensionalDoorBlockRegistrar.<init>(DimensionalDoorBlockRegistrar.java:41)
	at org.dimdev.dimdoors.DimensionalDoorsInitializer.onInitialize(DimensionalDoorsInitializer.java:137)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 17 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414)
	... 21 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [pehkui.mixins.json:reach.compat.client.GameRendererMixin from mod pehkui] from phase [DEFAULT] in config [pehkui.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 24 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Variable modifier target for net/minecraft/class_757::updateTargetedEntityFixDistance was removed by another injector [INJECT Applicator Phase -> pehkui.mixins.json:reach.compat.client.GameRendererMixin from mod pehkui -> Apply Injections ->  -> Inject -> pehkui.mixins.json:reach.compat.client.GameRendererMixin from mod pehkui->@ModifyVariable::updateTargetedEntityFixDistance(DF)D]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:169)
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more

**Comment by batmanatorul** [comment]
Yes, it is a conflict between minesettlements and pekhui and i don't think i can solve this one, sorry.

**Comment by batmanatorul** [comment]
Also next time you post a bug report please use the bug report template
